import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { parseChecksums, expectedFor, sha256File, verifyFile } from '../src/checksums.mjs';
import { ChecksumParseError, ChecksumMissingError, ChecksumMismatchError } from '../src/errors.mjs';

// sha256 of "hello\n" — the canonical digest for this input.
const HELLO_DIGEST = '5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03';
const ASSET = 'promptdecode-linux-amd64';

test('text-mode sha256sum lines ("<digest>  <name>") parse', () => {
  const map = parseChecksums(`${HELLO_DIGEST}  ${ASSET}\n`);
  // parseChecksums returns a Map (the rest of this file uses .get/.size on
  // it); spreading a Map into an object literal always yields {}, so compare
  // the Map itself.
  assert.deepStrictEqual(map, new Map([[ASSET, HELLO_DIGEST]]));
  assert.strictEqual(map.get(ASSET), HELLO_DIGEST);
});

test('binary-mode lines ("<digest> *<name>") parse and digests are lowercased', () => {
  const map = parseChecksums(`${HELLO_DIGEST.toUpperCase()} *${ASSET}\n`);
  assert.strictEqual(map.get(ASSET), HELLO_DIGEST);
});

test("a leading './' on names is stripped, comments and blank lines ignored", () => {
  const text = [
    '# generated by sha256sum',
    '',
    `${HELLO_DIGEST}  ./${ASSET}`,
    '   ',
    `${'a'.repeat(64)}  other-file`,
  ].join('\n');
  const map = parseChecksums(text);
  assert.strictEqual(map.size, 2);
  assert.strictEqual(map.get(ASSET), HELLO_DIGEST);
});

test('CRLF line endings are tolerated', () => {
  const map = parseChecksums(`${HELLO_DIGEST}  ${ASSET}\r\n`);
  assert.strictEqual(map.get(ASSET), HELLO_DIGEST);
});

test('a malformed line throws ChecksumParseError', () => {
  const bad = [
    'shortdigest  name',                            // digest too short
    `${HELLO_DIGEST.slice(0, 63)}a name`,           // one space separator only
    `zz${HELLO_DIGEST.slice(2)}  ${ASSET}`,         // non-hex character
    'no digest here at all',                        // not even close
  ];
  for (const line of bad) {
    assert.throws(() => parseChecksums(line), (error) => {
      assert.ok(error instanceof ChecksumParseError);
      assert.strictEqual(error.code, 'CHECKSUM_PARSE');
      return true;
    });
  }
});

test('a duplicate name throws ChecksumParseError', () => {
  const other = 'b'.repeat(64);
  assert.throws(
    () => parseChecksums(`${HELLO_DIGEST}  ${ASSET}\n${other}  ${ASSET}\n`),
    (error) => {
      assert.ok(error instanceof ChecksumParseError);
      assert.strictEqual(error.code, 'CHECKSUM_PARSE');
      return true;
    },
  );
});

test('expectedFor returns the digest when the asset is listed', () => {
  const map = parseChecksums(`${HELLO_DIGEST}  ${ASSET}\n`);
  assert.strictEqual(expectedFor(map, ASSET), HELLO_DIGEST);
});

test('a missing entry throws ChecksumMissingError — fail closed, never undefined', () => {
  const map = parseChecksums(`${HELLO_DIGEST}  other-file\n`);
  assert.throws(() => expectedFor(map, ASSET), (error) => {
    assert.ok(error instanceof ChecksumMissingError);
    assert.strictEqual(error.code, 'CHECKSUM_MISSING');
    assert.ok(error.message.includes(ASSET));
    return true;
  });
});

test('sha256File matches the known digest of a real temp file', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'pd-checksums-'));
  t.after(() => rm(dir, { recursive: true, force: true }));

  const file = join(dir, 'sample.txt');
  await writeFile(file, 'hello\n');
  assert.strictEqual(await sha256File(file), HELLO_DIGEST);
});

test('sha256File streams a larger file correctly without loading it whole', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'pd-checksums-'));
  t.after(() => rm(dir, { recursive: true, force: true }));

  // A few MB, so the stream sees many chunks.
  const chunk = Buffer.alloc(1024 * 1024, 0x5a);
  const file = join(dir, 'big.bin');
  const buffer = Buffer.concat(Array.from({ length: 5 }, () => chunk));
  await writeFile(file, buffer);
  assert.strictEqual(await sha256File(file), createHash('sha256').update(buffer).digest('hex'));
});

test('verifyFile resolves when the digest matches (case-insensitively)', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'pd-checksums-'));
  t.after(() => rm(dir, { recursive: true, force: true }));

  const file = join(dir, 'sample.txt');
  await writeFile(file, 'hello\n');
  await assert.doesNotReject(verifyFile(file, HELLO_DIGEST));
  await assert.doesNotReject(verifyFile(file, HELLO_DIGEST.toUpperCase()));
});

test('verifyFile throws ChecksumMismatchError carrying both digests', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'pd-checksums-'));
  t.after(() => rm(dir, { recursive: true, force: true }));

  const file = join(dir, 'sample.txt');
  await writeFile(file, 'hello\n');
  const tampered = 'f'.repeat(64);
  await assert.rejects(verifyFile(file, tampered), (error) => {
    assert.ok(error instanceof ChecksumMismatchError);
    assert.strictEqual(error.code, 'CHECKSUM_MISMATCH');
    assert.strictEqual(error.path, file);
    assert.strictEqual(error.expected, tampered);
    assert.strictEqual(error.actual, HELLO_DIGEST);
    return true;
  });
});

test('sha256File rejects on a missing file instead of resolving a bogus digest', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'pd-checksums-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  await mkdir(dir, { recursive: true });
  await assert.rejects(sha256File(join(dir, 'does-not-exist')));
});
